knownsec/pocsuite3

- pocsuite3/lib/request/patch/hook_request.py
> Fix hook_request

- pocsuite3/lib/core/interpreter_option.py
```python
In [1]: from pocsuite3.lib.core.interpreter_option import OptString                                                                                                                                                                                                                                                                                                  
In [2]: a = OptString("", "HTTP Referer header value")                                                                                                                                                                                                                                                                                                               
In [3]: a …
```
> Update Option iter func

- pocsuite3/lib/controller/controller.py
- pocsuite3/lib/core/plugin.py
- pocsuite3/plugins/file_record.py
New feature for #18 增加文件结果实时保存Demo
> New feature for #18

- pocsuite3/api/__init__.py
- pocsuite3/lib/utils/__init__.py
- pocsuite3/pocs/thinkphp_rce2.py
- tests/test_generate_shellcode_list.py
> Platform support

- pocsuite3/lib/core/common.py
- pocsuite3/lib/core/option.py
- pocsuite3/lib/parse/cmd.py
替换optparse，增加直接在命令行跑多ip和多poc的功能
> feat: 命令行增加多ip多poc的支持

- docs/CODING.md
- pocsuite3/lib/core/option.py
i think one poc file not found should not affect whole scan flow
> Optimize load poc

- pocsuite3/lib/core/interpreter.py
Pocsuite3 (pocs/thinkphp_rce2) > show ip
use
+-------+---------------+
|   Index  |          IP             |
+-------+---------------+
|     0       |    xx.xx.x.xxx    |
+-------+---------------+
Pocsuite3 (pocs/thinkphp_rce2) > set lhost 0
[16:34:20] [INFO] lhost => xx.xx.x.xxx
> 功能增强 show ip 命令后可以使用 set lhost index

- pocsuite3/lib/core/option.py
- pocsuite3/lib/core/update.py
> fix: update function

- pocsuite3/lib/core/threads.py
> 修改日志单词拼写错误以及写入空日志的问题

- pocsuite3/modules/fofa/__init__.py
> 修复 fofa web 模式 https 未加入目标

- docs/USAGE.md
- pocsuite3/data/user-agents.txt
- pocsuite3/lib/core/option.py
- pocsuite3/lib/parse/cmd.py
- pocsuite3/lib/request/patch/hook_request.py
使用 random-agent 后每次请求user-agent 换一次
user-agents.txt 增加 100 个 ua 头
修改部分文档
> Add random agent

- pocsuite3/lib/controller/controller.py
- pocsuite3/lib/core/common.py
- pocsuite3/lib/core/option.py
- pocsuite3/lib/core/poc.py
- pocsuite3/modules/listener/reverse_tcp.py
> refactory --verify mode ppt option code, add --shell mode ppt option support

- pocsuite3/lib/helper/archieve/memoryzip.py
- pocsuite3/lib/helper/archieve/war.py
> Add War and InMemoryWar

- pocsuite3/plugins/poc_from_pocs.py
in pocsuite3/plugins/poc_from_pocs.py
> fix a mistake of output for plugin

- pocsuite3/lib/request/patch/hook_request.py
hook request 导致调用了两次 merge_setting 合并头部，设置为 None 的头部在第一次被删除，然后第二次又被默认值填充。所以新建了一个内部函数，在第一次合并头部时保留 None。
> fix #139: Correctly remove headers that are set to None

- pocsuite3/lib/core/threads.py
> fix: isAlive()

- pocsuite3/modules/fofa/__init__.py
> #187 fix fofa search

- manpages/pocsuite.1
- pocsuite3/lib/core/option.py
- pocsuite3/lib/core/poc.py
- pocsuite3/lib/core/settings.py
- pocsuite3/lib/parse/cmd.py
The PR can solve the problem for #203
> feat(): add show definition options for poc

- CHANGELOG.md
- manpages/poc-console.1
- manpages/pocsuite.1
- pocsuite3/__init__.py
- pocsuite3/lib/core/common.py
- pocsuite3/lib/core/interpreter.py
- pocsuite3/lib/core/option.py
- pocsuite3/modules/httpserver/__init__.py
- pocsuite3/modules/listener/reverse_tcp.py
- setup.py
> Made some improvements with ip address related issues

- CHANGELOG.md
- docs/CODING.md
- manpages/poc-console.1
- manpages/pocsuite.1
- pocsuite3/__init__.py
- pocsuite3/lib/core/register.py
- setup.py
- tests/test_check_install_requires.py
use the pkg_resources  to find the version of a built-in module gives error, so add exception handling for robustness.
> chore: add testcase & update docs

- pocsuite3/lib/core/common.py
> fix: abstract base classes in collections were moved to collections.abc

- pocsuite3/lib/helper/archieve/jar.py
> Demarks in the jar file

- README.md
- pocsuite3/api/__init__.py
- pocsuite3/modules/interactsh/__init__.py
- requirements.txt
- setup.py
- tests/test_interactsh_module.py
https://github.com/projectdiscovery/interactsh
Interactsh is an Open-Source Solution for Out of band Data Extraction, A tool designed to detect bugs that cause external interactions, For example - Blind SQLi, Blind CMDi, SSRF, etc.
> feat: integrate with interactsh

- pocsuite3/modules/censys/__init__.py
> refactor: rewrite censys module

- CHANGELOG.md
- COPYING
- pocsuite3/__init__.py
- pocsuite3/lib/request/patch/__init__.py
- pocsuite3/lib/request/patch/hook_request.py
- pocsuite3/lib/request/patch/hook_urllib3_parse_url.py
- pocsuite3/lib/request/patch/unquote_request_uri.py
- setup.py
1. Fix urllib3 Issue with Parsing URIs - Breaks Security Tools when testing for Path Traversal，https://github.com/urllib3/urllib3/issues/1790
1. **Prevent url encoding**
3. fix #268
> feat: add hook for urllib3 and requests

- pocsuite3/modules/fofa/__init__.py
> fix: fofa query over multiple pages

- CHANGELOG.md
- manpages/poc-console.1
- manpages/pocsuite.1
- pocsuite3/__init__.py
- pocsuite3/lib/core/common.py
- pocsuite3/lib/core/interpreter.py
- pocsuite3/lib/core/log.py
- pocsuite3/modules/listener/reverse_tcp.py
- setup.py
> fix: Colorizing doesn't work on Windows with poc-console

- pocsuite3/modules/httpserver/__init__.py
> fix: httpserver module hangs on macos platform

- pocsuite3/lib/core/poc.py
> fix: auto correction of url protocol based on status code

- pocsuite3/lib/core/poc.py
> fix: url redirect problem in _check method

- pocsuite3/lib/core/interpreter.py
> fix: use command in console mode use absolute path
